"""Domestic-only dashboard environment settings schema."""

from __future__ import annotations

from typing import Any


def _as_bool(value: Any) -> bool:
    return str(value).lower() in ("1", "true", "yes", "on")


ENV_FIELDS = [
 {'key': 'DOMESTIC_STOCK_BROKER', 'label': '국내주식 증권사', 'type': 'select', 'hint': '국내주식 조회·주문에 사용할 증권사입니다.', 'options': ['namuh'], 'secret': False, 'restart_required': True},
 {'key': 'NHPLUG_ENVIRONMENT', 'label': 'NHPLUG 거래 환경', 'type': 'select', 'hint': 'mock=모의투자, live=실전투자 환경입니다.', 'options': ['mock', 'live'], 'secret': False, 'restart_required': True},
 {'key': 'NHPLUG_ACCOUNT', 'label': '나무 계좌번호', 'type': 'text', 'hint': '현재 NHPLUG 거래 환경과 일치하는 계좌번호입니다.', 'options': [], 'secret': False, 'restart_required': True},
 {'key': 'NHPLUG_APP_KEY', 'label': 'NHPLUG App Key', 'type': 'secret', 'hint': '나무증권 NHPLUG 포털에서 발급받은 앱 키입니다.', 'options': [], 'secret': True, 'restart_required': True},
 {'key': 'NHPLUG_APP_SECRET', 'label': 'NHPLUG App Secret', 'type': 'secret', 'hint': '나무증권 NHPLUG 포털에서 발급받은 앱 시크릿입니다.', 'options': [], 'secret': True, 'restart_required': True},{'key': 'TRADING_ENV',
  'label': '거래 환경',
  'type': 'select',
  'options': ['demo', 'real'],
  'hint': 'demo=모의투자, real=실전투자 환경입니다.',
  'secret': False,
  'restart_required': True},
 {'key': 'DRY_RUN',
  'label': '주문 차단 모드',
  'type': 'bool',
  'hint': 'true이면 실제 나무 주문 API를 호출하지 않습니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'ENABLE_LIVE_TRADING',
  'label': '실전 주문 허용',
  'type': 'bool',
  'hint': '실전 환경에서 실제 주문을 허용하는 최종 보호 스위치입니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'REQUIRE_APPROVAL',
  'label': '주문 승인 필요',
  'type': 'bool',
  'hint': 'true이면 주문을 승인 대기열에 먼저 등록합니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'ONLINE_ACCESS_BLOCKED',
  'label': '온라인 접속 차단',
  'type': 'bool',
  'hint': 'true이면 외부 API, 웹소켓, 시세 갱신과 모든 주문 실행을 차단합니다. DB 저장 정보는 계속 표시됩니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'SPLIT_N',
  'label': '분할 매수 횟수',
  'type': 'int',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'STOP_LOSS_PCT',
  'label': '손절 기준 %',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'TAKE_PROFIT',
  'label': '익절 기준 %',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'RSI_BUY',
  'label': 'RSI 매수 기준',
  'type': 'int',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'RSI_SELL',
  'label': 'RSI 매도 기준',
  'type': 'int',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'TRAILING_STOP_ACTIVATION_PCT',
  'label': '트레일링 활성 수익률 %',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'TRAILING_STOP_PCT',
  'label': '고점 대비 청산 하락률 %',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'TRAILING_STOP_LOOKBACK',
  'label': '트레일링 참고 기간',
  'type': 'int',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'TRADE_VALUE_SURGE_RATIO',
  'label': '거래대금 급등 배수',
  'type': 'float',
  'hint': '당일 거래대금이 직전 20일 평균의 몇 배 이상일 때 가점할지 설정합니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'FIRST_WAVE_MIN_PCT',
  'label': '1차 파동 최소 상승률 %',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'FIRST_WAVE_PULLBACK_MIN_PCT',
  'label': '눌림목 최소 조정률 %',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'FIRST_WAVE_PULLBACK_MAX_PCT',
  'label': '눌림목 최대 조정률 %',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'TOTAL_CAPITAL',
  'label': '총 운용 자금',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'ACCOUNT_INITIAL_CAPITAL',
  'label': '계좌 초기자산',
  'type': 'float',
  'hint': '총자산 대비 전체 손익을 계산하는 표시 기준이며 주문 규모에는 영향을 주지 않습니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'MAX_POSITIONS',
  'label': '최대 보유 종목 수',
  'type': 'int',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'MAX_SINGLE_WEIGHT',
  'label': '종목당 최대 비중',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'CASH_BUFFER',
  'label': '현금 보유 비중',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'MAX_DAILY_LOSS_PCT',
  'label': '일 최대 손실 %',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'HANSTOCK_EXCLUDED_SYMBOLS',
  'label': 'Hanstock Excluded Symbols',
  'type': 'text',
  'hint': 'Comma-separated domestic stock codes excluded from automated scans and orders.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'SCAN_UNIVERSE_SIZE',
  'label': '스캔 종목 수',
  'type': 'int',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'TRADE_DB_PATH',
  'label': '거래 DB 경로',
  'type': 'text',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'ACTIVE_MODEL_VERSION',
  'label': '활성 모델 버전',
  'type': 'text',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'AI_STRATEGY_ENABLED',
  'label': 'AI 전략 사용',
  'type': 'bool',
  'hint': 'true이면 후보 평가에 OpenAI 모델 점수를 함께 사용합니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'AI_SCORE_WEIGHT',
  'label': 'AI 점수 반영 비중',
  'type': 'float',
  'hint': '0~1 사이 값입니다. 0.4이면 룰 60%, AI 40%로 계산합니다.',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'AI_MIN_MODEL_CONFIDENCE',
  'label': 'AI 최소 신뢰도',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'AI_REQUIRE_BACKTEST_PASS',
  'label': '백테스트 통과 필수',
  'type': 'bool',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'AI_AUTO_APPROVE',
  'label': 'AI 자동 승인',
  'type': 'bool',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'AI_MIN_RULE_SCORE',
  'label': 'AI 최소 룰 점수',
  'type': 'float',
  'hint': 'OpenAI 호출 전 필터링할 최소 룰 점수입니다 (기본 1.5).',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'AI_ALLOW_CANDIDATE_PROMOTION',
  'label': 'AI 후보 승격 허용',
  'type': 'bool',
  'hint': 'true이면 룰 미달 종목도 AI 점수를 바탕으로 승급합니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'OPENAI_API_KEY',
  'label': 'OpenAI API Key',
  'type': 'secret',
  'hint': 'gpt-5-mini 호출에 사용할 OpenAI API 키입니다.',
  'options': [],
  'secret': True,
  'restart_required': False},
 {'key': 'OPENAI_MODEL',
  'label': 'OpenAI 모델',
  'type': 'text',
  'hint': '예: gpt-5-mini',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'OPENAI_TIMEOUT_SECONDS',
  'label': 'OpenAI 응답 제한초',
  'type': 'float',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'AI_CANDIDATE_LIMIT',
  'label': 'AI 평가 후보 수',
  'type': 'int',
  'hint': '',
  'options': [],
  'secret': False,
  'restart_required': False},
 {'key': 'SLACK_WEBHOOK_URL',
  'label': 'Slack Webhook URL',
  'type': 'secret',
  'hint': '',
  'options': [],
  'secret': True,
  'restart_required': True},
 {'key': 'RSI_RISK_PER_TRADE_PCT',
  'label': 'RSI 종목당 위험 한도',
  'type': 'float',
  'hint': '한 종목의 최초 손절가까지 허용하는 TOTAL_CAPITAL 대비 최대 위험 비율입니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'RSI_MAX_TOTAL_OPEN_RISK_PCT',
  'label': 'RSI 전체 오픈 위험 한도',
  'type': 'float',
  'hint': 'RSI 전략 보유종목의 미청산 손절 위험 합계 한도입니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'ALPHA_HA_RISK_PER_TRADE_PCT',
  'label': '알파 종목당 위험 한도',
  'type': 'float',
  'hint': '한 종목의 최초 손절가까지 허용하는 TOTAL_CAPITAL 대비 최대 위험 비율입니다.',
  'options': [],
  'secret': False,
  'restart_required': True},
 {'key': 'ALPHA_HA_MAX_TOTAL_OPEN_RISK_PCT',
  'label': '알파 전체 오픈 위험 한도',
  'type': 'float',
  'hint': '알파 전략 보유종목의 미청산 손절 위험 합계 한도입니다.',
  'options': [],
  'secret': False,
  'restart_required': True}]

STRATEGY_ENV_BINDINGS = {
    "SPLIT_N": ("split_n", "SPLIT_N", int),
    "STOP_LOSS_PCT": ("stop_loss_pct", "STOP_LOSS_PCT", float),
    "TAKE_PROFIT": ("take_profit", "TAKE_PROFIT", float),
    "RSI_BUY": ("rsi_buy", "RSI_BUY", int),
    "RSI_SELL": ("rsi_sell", "RSI_SELL", int),
    "TRAILING_STOP_ACTIVATION_PCT": ("trailing_stop_activation_pct", None, float),
    "TRAILING_STOP_PCT": ("trailing_stop_pct", None, float),
    "TRAILING_STOP_LOOKBACK": ("trailing_stop_lookback", None, int),
    "TRADE_VALUE_SURGE_RATIO": ("trade_value_surge_ratio", None, float),
    "FIRST_WAVE_MIN_PCT": ("first_wave_min_pct", None, float),
    "FIRST_WAVE_PULLBACK_MIN_PCT": ("first_wave_pullback_min_pct", None, float),
    "FIRST_WAVE_PULLBACK_MAX_PCT": ("first_wave_pullback_max_pct", None, float),
    "TOTAL_CAPITAL": ("total_capital", None, float),
    "MAX_POSITIONS": ("max_positions", None, int),
    "MAX_SINGLE_WEIGHT": ("max_single_weight", "MAX_SINGLE_WEIGHT", float),
    "CASH_BUFFER": ("cash_buffer", "CASH_BUFFER", float),
    "MAX_DAILY_LOSS_PCT": ("max_daily_loss_pct", "MAX_DAILY_LOSS_PCT", float),
    "HANSTOCK_EXCLUDED_SYMBOLS": ("hanstock_excluded_symbols", None, str),
    "SCAN_UNIVERSE_SIZE": ("scan_universe_size", "SCAN_UNIVERSE_SIZE", int),
    "RSI_RISK_PER_TRADE_PCT": ("rsi_risk_per_trade_pct", None, float),
    "RSI_MAX_TOTAL_OPEN_RISK_PCT": ("rsi_max_total_open_risk_pct", None, float),
    "ALPHA_HA_RISK_PER_TRADE_PCT": ("alpha_ha_risk_per_trade_pct", None, float),
    "ALPHA_HA_MAX_TOTAL_OPEN_RISK_PCT": ("alpha_ha_max_total_open_risk_pct", None, float),
}

AI_ENV_BINDINGS = {
    "AI_STRATEGY_ENABLED": ("ai_strategy_enabled", _as_bool),
    "AI_SCORE_WEIGHT": ("ai_score_weight", float),
    "AI_MIN_MODEL_CONFIDENCE": ("ai_min_model_confidence", float),
    "AI_REQUIRE_BACKTEST_PASS": ("ai_require_backtest_pass", _as_bool),
    "AI_AUTO_APPROVE": ("ai_auto_approve", _as_bool),
    "AI_MIN_RULE_SCORE": ("ai_min_rule_score", float),
    "AI_ALLOW_CANDIDATE_PROMOTION": ("ai_allow_candidate_promotion", _as_bool),
    "OPENAI_API_KEY": ("openai_api_key", str),
    "OPENAI_MODEL": ("openai_model", str),
    "OPENAI_TIMEOUT_SECONDS": ("openai_timeout_seconds", float),
    "AI_CANDIDATE_LIMIT": ("ai_candidate_limit", int),
}

BROKER_ENV_BINDINGS = {
    "DOMESTIC_STOCK_BROKER": ("domestic_stock_broker", str),
    "NHPLUG_ENVIRONMENT": ("nhplug_environment", str),
    "NHPLUG_ACCOUNT": ("nhplug_account", str),
    "NHPLUG_MOCK_ACCOUNT": ("nhplug_mock_account", str),
    "NHPLUG_LIVE_ACCOUNT": ("nhplug_live_account", str),
    "NHPLUG_LIVE_FALLBACK": ("nhplug_live_fallback", _as_bool),
    "NHPLUG_APP_KEY": ("nhplug_app_key", str),
    "NHPLUG_APP_SECRET": ("nhplug_app_secret", str),
}

for field in ENV_FIELDS:
    field["runtime_binding"] = (
        STRATEGY_ENV_BINDINGS.get(field["key"])
        or AI_ENV_BINDINGS.get(field["key"])
        or BROKER_ENV_BINDINGS.get(field["key"])
    )

ENV_FIELD_MAP = {field["key"]: field for field in ENV_FIELDS}
