"""Autonomous strategy domain contracts.

This package contains strategy-authored intent only.  Final quantities and
permission to place an order belong to the deterministic risk and execution
layers.
"""

from .models import (
    EntryPlan,
    ExitPlan,
    ExitTarget,
    InvalidationPlan,
    OrderPlan,
    OrderType,
    TimeInForce,
    TradeAction,
    TradeIntent,
    TrailingStopPlan,
)
from .validation import IntentValidationError, validate_trade_intent
from .risk_envelope import RiskDecision, RiskEnvelope, RiskLimits, RiskSnapshot
from .lifecycle import (
    LifecycleDecision,
    LifecyclePolicy,
    StrategyHealth,
    StrategyLifecycleGate,
    StrategyRepositoryCatalog,
)
from .orchestrator import (
    AutonomousStrategyOrchestrator,
    CycleResult,
    IntentResult,
    MarketContext,
    PortfolioContext,
    StrategyAdapter,
)
from .order_state import (
    BrokerCancellation,
    BrokerGateway,
    BrokerSubmission,
    ManagedOrderService,
    OrderStatus,
)
from .ai_planner import (
    AutonomousAIAdapter,
    OpenAIResponsesPlanner,
    PlannerError,
    PlannerProvider,
    PlannerResponse,
    TRADE_INTENT_JSON_SCHEMA,
    trade_intent_from_payload,
)
from .protection import (
    HardStopProtectionService,
    ProtectionAck,
    ProtectionBroker,
    PaperProtectionBroker,
    UnavailableProtectionBroker,
    ProtectionError,
    ProtectionGateSignal,
    ProtectionObservation,
    ProtectionRequest,
)
from .recovery import AutonomousRecoveryService, ProtectionRecoveryResult
from .continuous_service import (
    ApprovalPlanQueue,
    ContextProvider,
    ContinuousStrategyService,
    MarketCycleResult,
    RecoveryHooks,
    StartupRecoveryResult,
)
from .regime import (
    MarketRegime,
    MarketRegimeClassifier,
    MarketRegimeInput,
    MarketSnapshotBuilder,
    PortfolioBuildInput,
    PortfolioSnapshotBuilder,
    RegimeDecision,
    RegimeThresholds,
    SnapshotBuildError,
    TrustedSnapshotContextProvider,
)
from .health import (
    RepositoryHealthSource,
    StrategyHealthPolicy,
    StrategyHealthReport,
    StrategyHealthService,
)
from .broker_adapters import (
    BrokerObservedStatus,
    BrokerOrderSnapshot,
    KRBrokerGateway,
    ManagedOrderReconciler,
    ReconciliationResult,
    USBrokerGateway,
)
from .approval_bridge import (
    ApprovalPlanResult,
    ApprovalBridgeError,
    FreshRiskSnapshotProvider,
    ManagedApprovalBridge,
    ManagedApprovalPlanService,
    ManagedExecutionCoordinator,
)
from .runtime import (
    AutonomyRuntime,
    RuntimeConfigurationError,
    RuntimeResult,
    build_runtime_contexts,
    run_autonomous_strategy,
)
from .operational_context import (
    OperationalSnapshot,
    OperationalSnapshotProvider,
    assemble_operational_run_once,
)
from .daily_equity import DailyEquityResult, DailyEquityService

__all__ = [
    "EntryPlan",
    "ExitPlan",
    "ExitTarget",
    "IntentValidationError",
    "IntentResult",
    "InvalidationPlan",
    "MarketContext",
    "MarketRegime",
    "MarketRegimeClassifier",
    "MarketRegimeInput",
    "MarketSnapshotBuilder",
    "LifecycleDecision",
    "LifecyclePolicy",
    "BrokerCancellation",
    "BrokerGateway",
    "BrokerSubmission",
    "ApprovalBridgeError",
    "ApprovalPlanQueue",
    "ApprovalPlanResult",
    "FreshRiskSnapshotProvider",
    "BrokerObservedStatus",
    "BrokerOrderSnapshot",
    "KRBrokerGateway",
    "ManagedOrderService",
    "ManagedOrderReconciler",
    "ManagedApprovalBridge",
    "ManagedApprovalPlanService",
    "ManagedExecutionCoordinator",
    "HardStopProtectionService",
    "OrderPlan",
    "OrderType",
    "PortfolioContext",
    "PortfolioBuildInput",
    "PortfolioSnapshotBuilder",
    "OrderStatus",
    "ProtectionAck",
    "ProtectionBroker",
    "PaperProtectionBroker",
    "UnavailableProtectionBroker",
    "ProtectionError",
    "ProtectionGateSignal",
    "ProtectionObservation",
    "ProtectionRequest",
    "ProtectionRecoveryResult",
    "RiskDecision",
    "RiskEnvelope",
    "RiskLimits",
    "RiskSnapshot",
    "RepositoryHealthSource",
    "RegimeDecision",
    "RegimeThresholds",
    "ReconciliationResult",
    "RuntimeConfigurationError",
    "RuntimeResult",
    "StrategyAdapter",
    "StrategyHealth",
    "StrategyHealthPolicy",
    "StrategyHealthReport",
    "StrategyHealthService",
    "StrategyLifecycleGate",
    "StrategyRepositoryCatalog",
    "TimeInForce",
    "TradeAction",
    "TradeIntent",
    "USBrokerGateway",
    "TrailingStopPlan",
    "AutonomousStrategyOrchestrator",
    "AutonomousRecoveryService",
    "AutonomousAIAdapter",
    "AutonomyRuntime",
    "CycleResult",
    "ContextProvider",
    "ContinuousStrategyService",
    "MarketCycleResult",
    "RecoveryHooks",
    "StartupRecoveryResult",
    "SnapshotBuildError",
    "TrustedSnapshotContextProvider",
    "OpenAIResponsesPlanner",
    "PlannerError",
    "PlannerProvider",
    "PlannerResponse",
    "TRADE_INTENT_JSON_SCHEMA",
    "trade_intent_from_payload",
    "build_runtime_contexts",
    "run_autonomous_strategy",
    "OperationalSnapshot",
    "OperationalSnapshotProvider",
    "assemble_operational_run_once",
    "DailyEquityResult",
    "DailyEquityService",
    "validate_trade_intent",
]
